<a href="https://colab.research.google.com/github/annakaminska9898/data-science-bootcamp/blob/main/algebra_linowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#ALGEBRA LINIOWA

import numpy as np

v1 = np.array([-1,4])
v1


array([-1,  4])

In [7]:

np.linalg.norm(v1)

4.123105625617661

In [8]:
v2= np.array([-10,10,13])

In [10]:
np.linalg.norm(v2)

19.209372712298546

In [17]:
#odległość dwóch punktów na płaszczyźnie
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p - q)

5.0

In [18]:
#odległość dwch punktów w przestzreni
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

In [21]:
#mnorzenie macierzy 

x= np.array([[5,3],[3,9]])
y= np.array([[1],[-1]])
print(x, '\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [22]:
z = np.dot(x,y)
z

array([[ 2],
       [-6]])

In [23]:
x.shape

(2, 2)

In [24]:
y.shape

(2, 1)

In [25]:
z.shape

(2, 1)

In [28]:
x = np.array([[2,3,5],
              [3,4,5]])
y= np.array([[3,4,6],
             [5,6,7],
             [7,8,9]])

print(x, '\n')
print(y)

[[2 3 5]
 [3 4 5]] 

[[3 4 6]
 [5 6 7]
 [7 8 9]]


In [29]:
np.dot(x,y)

array([[56, 66, 78],
       [64, 76, 91]])

In [32]:
#wyznacznik macierzy

A= np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10

In [33]:
#ślad macierzy

np.trace(A)

5

In [34]:
#macierz jednostkowa

np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#macierz odwrotna

A

array([[ 2,  4],
       [-1,  3]])

In [37]:
B = np.linalg.inv(A)

In [38]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [41]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [42]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [43]:
#macierz transponowana

A

array([[ 2,  4],
       [-1,  3]])

In [44]:
A.T


array([[ 2, -1],
       [ 4,  3]])

In [ ]:
#UKŁADY RÓWNAŃ

